version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  db:
    container_name: my-mysql-container 
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --bind-address=0.0.0.0
